db.course.insert([
{
"CourseID":1,
"CourseName":"pkop",
"CourseRating":2,
"Course:Date":"09090909",
"Instruction":[
{
"Step":1,
"Instruction_detail":"kjjknnkjnknjjk",
"PhotoName":"jhbjhbjh",
"PhotoAddress":"jknjk",
},
{
"Step":2,
"Instruction_detail":"kjjknnkjnknjjk",
"PhotoName":"jhbjhbjh",
"PhotoAddress":"jknjk",
}
],

},
{
"CourseID":2,
"CourseName":"pkop",
"CourseRating":2,
"Course:Date":"09090909",
"Instruction":[
{
"Step":1,
"Instruction_detail":"kjjknnkjnknjjk",
"PhotoName":"jhbjhbjh",
"PhotoAddress":"jknjk",
},
{
"Step":3,
"Instruction_detail":"kjjknnkjnknjjk",
"PhotoName":"jhbjhbjh",
"PhotoAddress":"jknjk",
}
],

},
{
"CourseID":3,
"CourseName":"pkop",
"CourseRating":2,
"Course:Date":"09090909",
"Instruction":[
{
"Step":1,
"Instruction_detail":"kjjknnkjnknjjk",
"PhotoName":"jhbjhbjh",
"PhotoAddress":"jknjk",
},
{
"Step":4,
"Instruction_detail":"kjjknnkjnknjjk",
"PhotoName":"jhbjhbjh",
"PhotoAddress":"jknjk",
}
],

}
])